# -*- coding: utf-8 -*-
"""Clustering | Assignment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fjiAAuQ9YbQy-LhhcI7Qg4kp72eGxcJK

# **Assignment: Clustering**

---

# **Question 1: Difference between K-Means and Hierarchical Clustering**

### **Answer:**

| Aspect             | K-Means Clustering        | Hierarchical Clustering   |
| ------------------ | ------------------------- | ------------------------- |
| Approach           | Partition-based           | Tree-based                |
| Number of Clusters | Must specify K beforehand | No need initially         |
| Speed              | Faster                    | Slower                    |
| Output             | Flat clusters             | Dendrogram                |
| Scalability        | Good for large datasets   | Better for small datasets |

### **Use Cases:**

* **K-Means:** Customer segmentation in e-commerce
* **Hierarchical Clustering:** Gene analysis in bioinformatics

---

# **Question 2: Silhouette Score**

### **Answer:**

The **Silhouette Score** measures how well data points fit within their assigned cluster.

### **Range:**

* **+1** → Well-separated clusters
* **0** → Overlapping clusters
* **-1** → Incorrect clustering

### **Purpose:**

* Evaluate clustering quality
* Help choose the optimal number of clusters

### **Formula:**

[
S = \frac{b-a}{max(a,b)}
]

Where:

* **a** = intra-cluster distance
* **b** = nearest-cluster distance

---

# **Question 3: Core Parameters of DBSCAN**

### **Answer:**

### **1. eps (Epsilon)**

* Maximum distance between neighboring points

### **2. min_samples**

* Minimum points required to form a dense region

---

### **Influence on Clustering:**

* Small eps → More clusters/noise
* Large eps → Fewer clusters
* Large min_samples → Stricter clustering

---

# **Question 4: Importance of Feature Scaling**

### **Answer:**

Feature scaling ensures all features contribute equally during distance calculations.

### **Why Important:**

* K-Means uses Euclidean distance
* DBSCAN depends on density distances

### **Without Scaling:**

* Features with larger values dominate

### **Common Scaling Methods:**

* StandardScaler
* MinMaxScaler

---

# **Question 5: Elbow Method**

### **Answer:**

The **Elbow Method** helps determine the optimal number of clusters in K-Means.

### **Process:**

1. Run K-Means for multiple K values
2. Compute WCSS (Within Cluster Sum of Squares)
3. Plot K vs WCSS

### **Optimal K:**

* Point where reduction slows significantly (“elbow”)

---

# **Question 6: KMeans on make_blobs**

### **Answer:**

```python id="clust1"
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

# Generate data
X, y = make_blobs(n_samples=300, centers=4, random_state=42)

# KMeans
kmeans = KMeans(n_clusters=4, random_state=42)
labels = kmeans.fit_predict(X)

# Plot
plt.scatter(X[:,0], X[:,1], c=labels)
plt.scatter(kmeans.cluster_centers_[:,0],
            kmeans.cluster_centers_[:,1],
            s=300, c='red', marker='X')

plt.title("KMeans Clustering")
plt.show()
```

### **Output:**

* Four colored clusters
* Red X marks cluster centers

---

# **Question 7: DBSCAN on Wine Dataset**

### **Answer:**

```python id="clust2"
from sklearn.datasets import load_wine
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import DBSCAN

# Load data
data = load_wine()
X = data.data

# Scaling
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# DBSCAN
db = DBSCAN(eps=2, min_samples=5)
labels = db.fit_predict(X_scaled)

# Count clusters
n_clusters = len(set(labels)) - (1 if -1 in labels else 0)

print("Number of clusters:", n_clusters)
```

### **Output (Example):**

```id="clust2out"
Number of clusters: 3
```

---

# **Question 8: DBSCAN on make_moons**

### **Answer:**

```python id="clust3"
from sklearn.datasets import make_moons
from sklearn.cluster import DBSCAN
import matplotlib.pyplot as plt

# Generate data
X, y = make_moons(n_samples=200, noise=0.1, random_state=42)

# DBSCAN
db = DBSCAN(eps=0.2, min_samples=5)
labels = db.fit_predict(X)

# Plot
plt.scatter(X[:,0], X[:,1], c=labels, cmap='rainbow')

# Highlight outliers
outliers = labels == -1
plt.scatter(X[outliers,0], X[outliers,1],
            c='black', marker='x', s=100)

plt.title("DBSCAN with Outliers")
plt.show()
```

---

# **Question 9: PCA + Agglomerative Clustering**

### **Answer:**

```python id="clust4"
from sklearn.datasets import load_wine
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import AgglomerativeClustering
import matplotlib.pyplot as plt

# Load data
data = load_wine()
X = data.data

# Scaling
X_scaled = StandardScaler().fit_transform(X)

# PCA
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

# Agglomerative Clustering
agg = AgglomerativeClustering(n_clusters=3)
labels = agg.fit_predict(X_pca)

# Plot
plt.scatter(X_pca[:,0], X_pca[:,1], c=labels)
plt.title("Agglomerative Clustering")
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.show()
```

---

# **Question 10: Real-world Customer Segmentation Workflow**

### **Answer:**

## **1. Clustering Algorithms**

### **K-Means**

* Fast and effective for customer segmentation

### **DBSCAN**

* Detects unusual customer behavior/outliers

### **Hierarchical Clustering**

* Helps visualize customer relationships

---

## **2. Data Preprocessing**

### **Missing Values**

* Fill using mean/median

### **Encoding**

* Convert categorical features

### **Scaling**

* Use StandardScaler for equal importance

---

## **3. Determine Number of Clusters**

### **Methods:**

* Elbow Method
* Silhouette Score

---

## **4. Business Benefits**

* Personalized marketing
* Better recommendations
* Customer retention
* Targeted promotions

---

## **Python Code:**

```python id="clust5"
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score

# Example preprocessing
X_scaled = StandardScaler().fit_transform(X)

# KMeans
kmeans = KMeans(n_clusters=3)
labels = kmeans.fit_predict(X_scaled)

# Evaluation
score = silhouette_score(X_scaled, labels)

print("Silhouette Score:", score)
```

### **Output (Example):**

```id="clust5out"
Silhouette Score: 0.67
```
"""

from IPython.display import Image
Image('/content/54042d87-c2c9-4185-b37b-18fb3db406bd.jpg')

